vc-deploy-params: &vc-deploy-params
  ESXI_HOST: ((esxi_host))
  ESXI_USR: ((esxi_usr))
  ESXI_PWD: ((esxi_pwd))
  ESXI_DATASTORE: ((esxi_datastore))
  VC_DEPLOYMENT_SIZE: ((vc_deploy_size))
  VC_THIN_PROVISION: ((vc_thin_provision))
  VC_NET_MODE: ((vc_net_mode))
  VC_NAME: ((vc_name))
  VC_SYSTEM_NAME: ((vc_system_name)
  VC_IP: ((vc_ip_address))
  VC_NETMASK: ((vc_prefix))
  VC_DNS_SERVER: ((vc_dns_server))
  VC_GATEWAY: ((vc_gateway))
  VC_NTP_SERVER: ((vc_ntp_server))
  VC_PORTGROUP: ((vc_network)))
  VC_ROOT_PWD: ((vc_root_pass))
  VC_SSH_ENABLED: ((ssh_enabled))
  VC_SSO_PWD: ((sso_pass))
  VC_SSO_DOMAIN: ((sso_domain))
  CEIP_ENABLED: ((ceip_enabled))
  VC_ISO: ((vc_iso_file_name))

resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: vc-pipeline
  type: git
  source:
    uri: https://github.com/nvpnathan/vc-ci-pipeline.git
    branch: ((vc_install_branch))

- name: vc-ova
  type: file-url
  source:
    url: ((ova_webserver))/((vc_iso_file_name))
    filename: ((vc_iso_file_name))
    skip_ssl_verification: true

jobs:

- name: deploy-vc
  plan:
  - in_parallel:
    - get: vc-pipeline
    - get: vc-ova
  
  - task: deploy
    file: vc-pipeline/tasks/import-vc/task.yml
    params: *vc-deploy-params

