---

platform: linux

image_resource:
  type: docker-image
  source: {repository: dyanngg/nsx-t-gen-worker}

params:
  ESXI_HOST:
  ESXI_USR:
  ESXI_PWD:
  ESXI_DATASTORE:
  VC_DEPLOYMENT_SIZE:
  VC_THIN_PROVISION:
  VC_NET_MODE:
  VC_NAME:
  VC_SYSTEM_NAME:
  VC_IP:
  VC_NETMASK:
  VC_DNS_SERVER:
  VC_GATEWAY:
  VC_NTP_SERVER:
  VC_PORTGROUP:
  VC_ROOT_PWD:
  VC_SSH_ENABLED:
  VC_SSO_PWD:
  VC_SSO_DOMAIN:
  CEIP_ENABLED:
  VC_ISO:

inputs:
  - name: vc-pipeline
  - name: vc-ova

run:
  path: vc-ci-pipeline/tasks/import-vc/task.sh
